export { alphaNumeric } from './alpha-numeric';
export { aol } from './aol';
export { email } from './email';
export { maxLength15 as maxLength } from './max-length-15';
export { minLength2 as minLength } from './min-length-2';
export { minValue13 as minValue } from './min-value-13';
export { number } from './number';
export { phoneNumber } from './phone-number';
export { required } from './required';
export { tooYoung } from './too-young';
